name: mongo-deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  global_var: 'Global_Value'
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev-env
    env:
      job_var: Job_Value
      PORT: 8080
      MONGODB_CLUSTER_ADDRESS: mongo1.xwxl4f6.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USER }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASS }}
      #MONGODB_USERNAME: admin
      #MONGODB_PASSWORD: Kjf4doQhI5bsdczw
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: test the code
        run: npm test
      #- name: build the code
      #  run: npm run build

      - name: global variable
        run: |
          echo "Global value: $global_var"
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
      - name: job variable
        run: |
          echo "Job value: $job_var"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
