name: mongo-deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  global_var: 'Global_Value'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      job_var: Job_Value
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-deps-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: test the code
        run: npm test
      - name: build the code
        run: npm run build

      - name: global variable
        run: echo "Global value: $global_var"
      - name: job variable
        run: echo "Job value: $job_var"
